#ifndef _APP_CONFIG_H_
#define _APP_CONFIG_H_

#ifdef NDEBUG
	#define NRF_LOG_ENABLED 0
#else
	#define NRF_LOG_ENABLED 1
#endif
// <o> NRF_LOG_DEFAULT_LEVEL  - Default Severity level
// <0=> Off
// <1=> Error
// <2=> Warning
// <3=> Info
// <4=> Debug
#define NRF_LOG_DEFAULT_LEVEL 3

#define NRF_LOG_MSGPOOL_ELEMENT_COUNT 32
#define NRF_LOG_MSGPOOL_ELEMENT_SIZE 64
#define NRF_LOG_BACKEND_RTT_TEMP_BUFFER_SIZE 256
#define NRF_LOG_BACKEND_RTT_TX_RETRY_CNT 7
#define NRF_LOG_BACKEND_RTT_TX_RETRY_DELAY_MS 25
#define NRF_LOG_DEFERRED 1	// log buffer
#define NRF_LOG_BUFSIZE 1024
#define NRF_LOG_ALLOW_OVERFLOW 1

#define NRF_LOG_BACKEND_UART_ENABLED 0
#define NRF_LOG_BACKEND_RTT_ENABLED 1
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0
#define NRF_LOG_BACKEND_SERIAL_USES_RTT 1
#define NRF_FPRINTF_FLAG_AUTOMATIC_CR_ON_LF_ENABLED 0

#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_SDH_BLE_CENTRAL_LINK_COUNT 0
#define NRF_SDH_BLE_TOTAL_LINK_COUNT 1

#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 247
#define NRF_SDH_BLE_GAP_EVENT_LENGTH 16

#define WDT_ENABLED 1

#define APP_TIMER_ENABLED 1

#define NRF_QUEUE_ENABLED 1
#define RNG_ENABLED 1
#define NRFX_RNG_ENABLED 1


#define USE_RC_32K (1)

#if USE_RC_32K==1
	#define NRF_SDH_CLOCK_LF_SRC 0
	#define NRF_SDH_CLOCK_LF_ACCURACY 1
	#define NRF_SDH_CLOCK_LF_RC_CTIV 16
	#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 2
#else
	#define NRF_SDH_CLOCK_LF_SRC 1
	#define NRF_SDH_CLOCK_LF_ACCURACY 5
	#define NRF_SDH_CLOCK_LF_RC_CTIV 0
	#define NRF_SDH_CLOCK_LF_RC_TEMP_CTIV 0
#endif
//#define NRF_BLE_GATT_MAX_MTU_SIZE 23

//#define PEER_MANAGER_ENABLED 1

#define PWM_ENABLED 1
#define PWM0_ENABLED 1
#define PWM1_ENABLED 1
#define PWM2_ENABLED 1
#define APP_PWM_ENABLED 1

#define BLE_BAS_ENABLED 1
#define BLE_DIS_ENABLED 1
#define BLE_HIDS_ENABLED 1
#define BLE_ANCS_C_ENABLED 1
#define BLE_DFU_ENABLED 1
#define NRF_DFU_SVCI_ENABLED
#define NRF_DFU_TRANSPORT_BLE 1

// #define BLE_DB_DISCOVERY_ENABLED 1
#define NRF_BLE_GQ_ENABLED 1
#define NRF_BLE_GQ_GATTC_WRITE_MAX_DATA_LEN (64)
#define NRF_BLE_GQ_GATTS_HVX_MAX_DATA_LEN (96)
// #define APP_FIFO_ENABLED 1

#define NRFX_RTC_ENABLED 1
#define NRFX_RTC2_ENABLED 1
#define APP_TIMER_V2 1
#define APP_TIMER_KEEPS_RTC_ACTIVE 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 0

#define RTC_ENABLED 1
#define RTC2_ENABLED 1

#define APP_TIMER_CONFIG_USE_SCHEDULER 0	// hid工程自带
#define CRC16_ENABLED 1	// hid工程自带
#define FDS_ENABLED 1

#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 8
// #define APP_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1

#define BUTTON_ENABLED 1

#define SAADC_ENABLED 1
// #define NRFX_SAADC_ENABLED 1

#define FSTORAGE_ENABLED 1

#define UART_ENABLED 0

#define NRFX_WDT_ENABLED 1
#define NRFX_WDT_CONFIG_RELOAD_VALUE 3600

#define TIMER_ENABLED 1
#define TIMER0_ENABLED 1
#define TIMER1_ENABLED 1
#define TIMER2_ENABLED 1
#define TIMER_DEFAULT_CONFIG_FREQUENCY NRF_TIMER_FREQ_1MHz
#define TIMER_DEFAULT_CONFIG_MODE 0
#define TIMER_DEFAULT_CONFIG_BIT_WIDTH NRF_TIMER_BIT_WIDTH_32
#define TIMER_DEFAULT_CONFIG_IRQ_PRIORITY APP_IRQ_PRIORITY_LOW

#endif
